---
title: "Ethiopia LSMS-ISA"
author: "Elliot Quan"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(haven) # for converting .dta to .csv
```



```{r}
# auxiliary function for handling sums of NA vectors
# if all elements are NA return NA, else return sum of the non NA elements
sumNA <- function(x) {
  if (all(is.na(x))) {
    return(NA)
  } else {
    return(sum(x, na.rm=TRUE))
  }
}
```

```{r}
# sect3 is individual level data (fertilizer use)
sect3_pp_w1 <- read.csv('../LSMS/Ethiopia/2011-12/sect3_pp_w1.csv')
sect3_pp_w2 <- read.csv('../LSMS/Ethiopia/2013-14/2013-14_csv/sect3_pp_w2.csv')
sect3_pp_w3 <- read.csv('../LSMS/Ethiopia/2015-16/Post-Planting/sect3_pp_w3.csv')

# sect3 is household level (chemical fertilizer y/n)
sect7_pp_w1 <- read.csv('../LSMS/Ethiopia/2011-12/sect7_pp_w1.csv')
```

# Wave 1 (2011-2012)
```{r} 
wave1 <- sect3_pp_w1 %>% 
  select(household_id, pw, fert=pp_s3q14, urea=pp_s3q15, dap=pp_s3q18, manure=pp_s3q21, compost=pp_s3q23, organic_fert=pp_s3q25) %>% drop_na(fert)

# 1 encoded as YES
# change 2 to 0 NO
wave1[wave1==2] <- 0

# handling NAs - assume that if fert is 0 then no fertilizer was used
cols <- 3:ncol(wave1)
wave1[wave1$fert==0, 3:ncol(wave1)] <- 0

# at this point there are 978/20000+ rows that have missing values - we will drop, since affects very few households 
nrow(wave1[!complete.cases(wave1),])

wave1 <- wave1 %>%
  mutate(
    organic_fert_dummy = as.numeric((manure+compost+organic_fert) > 0),
         inorganic_fert_dummy = as.numeric((urea+dap) > 0),
    fert_dummy = as.numeric((fert+urea+dap+manure+compost)>0)) %>% drop_na()



```



```{r}
# compute number of uses per unique household_id/pw (one pw per household id, so valid)
by_hh <- wave1 %>% group_by(household_id, pw) %>%
  summarize_each(funs(sum(., na.rm=TRUE)))


# replace all values > 0 with 1 for computing average per household
by_hh[, -c(1, 2)] <- ifelse(by_hh[, -c(1, 2)] > 0, 1, 0)
colMeans(by_hh[, -c(1,2)])
```


## Using sampling weights
```{r}

# if using weights: not sure if done correctly!
weight_sum <- sum(by_hh$pw)
weighted <- by_hh[, -c(1,2)] * by_hh$pw
colSums(weighted)/weight_sum

num_households <- nrow(by_hh)
num_households
```



# s7 wave1 (chem. fert.) data

```{r}
s7 <- sect7_pp_w1 %>%
  select(household_id, pw, chem_fert=pp_s7q02)
s7[s7==2] <- 0
s7_by_hh <- s7 %>% group_by(household_id, pw) %>% summarize(chem_fert=sum(chem_fert, na.rm=TRUE) > 0)
s7_by_hh$chem_fert <- as.integer(s7_by_hh$chem_fert)
mean(s7_by_hh$chem_fert) # we see that without weighting, avg is 41%
s7_by_hh <- s7_by_hh %>% mutate(chem_fert_w=pw*chem_fert) 
sum(s7_by_hh$chem_fert_w)/sum(s7_by_hh$pw) # with weighting, avg is 54%
```




