---
title: "GAHI"
author: Elliot Quan
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r}
library(dplyr)
library(ggplot2)
```


```{r}
africa <- read.csv('../GAHI/data/africa_data.csv')

unique(africa$country_title)

```

```{r}
countries <- c('Burkina Faso', 'Ethiopia', 'Malawi', 'Mali', 'Niger', 'Nigeria', 'Tanzania', 'Uganda')
summary <- africa %>% filter(country_title == 'Ethiopia') %>% select(admin0, admin1, admin2)
summary
temp <- tolower(sort(unique(summary$admin2)))
```

```{r}
recode(temp, 'e. shewa' = 'east shewa', 'horo guduru' = 'horo gudru wellega', 'n. gonder' = 'north gondar', 'n. wello' = 'north wollo', 'north shoa zone' = 'north shewa', 's. gonder' = 'south gondar', 
       's. wello' = 'south wollo', 'segen' = 'konso special', 
       'w. harerge' = 'west hararge', 'west gojam' = 'west gojjam')
```




```{r}
eth_schisto <- africa %>% 
  filter(!is.na(number_positive) & !is.na(number_examined) ) %>%
  filter(country_title == 'Ethiopia') %>%
  group_by(country_title, publication_year, district=admin1, zone=admin2) %>% 
  summarize(num_pos=sum(number_positive), num_examined=sum(number_examined), prev=num_pos/num_examined) %>%
  mutate(prev = round(prev, digits=3)) %>% 
  rename(country=country_title, year=publication_year)

eth_schisto <- eth_schisto %>% mutate(zone=recode(tolower(zone), 'e. shewa' = 'east shewa', 'horo guduru' = 'horo gudru wellega', 'n. gonder' = 'north gondar', 'n. wello' = 'north wollo', 'north shoa zone' = 'north shewa', 's. gonder' = 'south gondar', 
       's. wello' = 'south wollo', 'segen' = 'konso special', 
       'w. harerge' = 'west hararge', 'west gojam' = 'west gojjam'))

eth_schisto
```


```{r}
write_csv(eth_schisto, '../results/eth_schisto.csv')
```



```{r, eval=FALSE}
write.csv(schisto_summary, file='GAHI_schisto.csv', row.names = FALSE)
```


```{r}

```




