---
title: "nigeria_lsms"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r}
library(sf)
library(readr)
library(dplyr)
library(tidyr)
library(dummies)
library(haven)
```


```{r}
# auxiliary function for handling sums of NA vectors
# handles NA by returning NA if all are NA
sumNA <- function(x) {
  if (all(is.na(x))) {
    return(NA)
  } else {
    return(sum(x, na.rm=TRUE))
  }
}

# take a vector of inputs: if at least 1 input is 1, then return 1 else 0.
# handles NA by returning NA if all are NA
indicator <- function(x) {
  if (all(is.na(x))) {
    return(NA)
  } else if (sum(x, na.rm=TRUE) > 0) {
    return(1)
  } else {
    return(0)
  }
}
```



# Shapefiles 

from GADM. data is at the 2nd administrative level (Local Govt Areas)

```{r}
nga_sf <- readRDS('../shapefiles/nga/GADM/gadm36_NGA_2_sf.rds')
st_crs(nga_sf)
```

# Geovars (location)

```{r}
loc1 <- read_csv("../lsms_data/nigeria/w1/NGA_HouseholdGeovariables_Y1.csv")
loc1

loc2 <- read_csv("../lsms_data/nigeria/w2/NGA_HouseholdGeovars_Y2.csv")
loc2 

loc3 <- read_csv("../lsms_data/nigeria/w3/nga_householdgeovars_y3.csv")
loc3

```

```{r}
loc1_f <- loc1 %>% select(hhid, longitude=lon_dd_mod, latitude = lat_dd_mod)
loc1_mappings <- unique(loc1_f)

loc2_f <- loc2 %>% select(hhid, longitude=lon_dd_mod, latitude = lat_dd_mod)
loc2_mappings <- unique(loc2_f)

loc3_f <- loc3 %>% select(hhid, longitude=LON_DD_MOD, latitude = LAT_DD_MOD)
loc3_mappings <- unique(loc3_f)
```


# Fertilizer data
## Wave 1 (2010-2011)



fertilizer 
```{r}
fert_w1 <- read_csv('../lsms_data/nigeria/w1/sect11d_plantingw1.csv')
fert_w2 <- read_csv('../lsms_data/nigeria/w2/sect11d_plantingw2.csv')
fert_w3 <- read_csv('../lsms_data/nigeria/w3/secta11d_harvestw3.csv')
```


```{r}
fert1 <- fert_w1 %>% select(zone, state, hhid, fert=s11dq1, 
                      type_fert=s11dq14) %>% drop_na(fert)
fert2 <- fert_w2 %>% select(zone, state, hhid, fert=s11dq1, 
                      type_fert=s11dq15) %>% drop_na(fert)
fert3 <- fert_w3 %>% select(zone, state, hhid, fert=s11dq1, 
                      type_fert=s11dq15) %>% drop_na(fert)

fert1_joined <- inner_join(fert1, loc1_mappings)
fert1_joined

fert2_joined <- inner_join(fert2, loc2_mappings)
fert2_joined

fert3_joined <- inner_join(fert3, loc3_mappings)
fert3_joined
```

```{r}
w1_fert <- data.frame(country="nigeria", start_yr = 2010, end_yr = 2011, fert1_joined, stringsAsFactors = F) 
w2_fert <- data.frame(country="nigeria", start_yr = 2012, end_yr = 2013, fert2_joined, stringsAsFactors = F)
w3_fert <- data.frame(country="nigeria", start_yr = 2015, end_yr = 2016, fert3_joined, stringsAsFactors = F)
fert <- rbind(w1_fert, w2_fert, w3_fert)
fert[!complete.cases(fert$longitude, fert$latitude), ]
```

```{r}
# join with sf data

fert_sf <- st_as_sf(x=fert, coords=c("longitude", "latitude"), crs = "+proj=longlat +datum=WGS84 +nodefs")
fert_joined <- st_join(nga_sf, fert_sf, left=FALSE)
fert_joined
```


```{r}
fert_df <- fert_joined %>% select(country, start_yr, end_yr, NAME_2, hhid, fert, type_fert) %>% st_set_geometry(NULL)
rownames(fert_df) <- 1:nrow(fert_df)
fert_df
```


```{r}
# replace 2s with 1s in fert
recode <- function(x) ifelse(x == 2 | x == 0, 0, 1)
fert_df <- fert_df %>% mutate_at(c("fert"), recode)

# if no fert used, then set type_fert to 0
fert_df[(fert_df$fert == 0) & !is.na(fert_df$fert), c("type_fert")] <- 0

# if fert used but not specified, then put other (set to 4)
fert_df[(fert_df$fert == 1) & is.na(fert_df$type_fert), "type_fert"] <- 4
fert_df
```

```{r}
fert_s11d <- cbind(fert_s11d, dummy(fert_s11d$type_fert, sep='_'))
fert_s11d
```


```{r}
fert_s11d_named <- fert_s11d %>% rename(no_fert=fert_s11d_0, npk=fert_s11d_1, urea=fert_s11d_2, composite_manure=fert_s11d_3, other=fert_s11d_4)
fert_s11d_named <- fert_s11d_named %>% select(-type_fert) %>% mutate(o_fert = composite_manure, io_fert = as.numeric((npk+urea) > 0)) 
fert_s11d_named 
```

```{r}
fert_s11d_named <- fert_s11d_named %>% select(-no_fert) %>% group_by(zone, state, hhid) %>% summarize_all(indicator) %>% drop_na()

w1_fert_avg <- fert_s11d_named %>% select(-hhid) %>% group_by(zone, state) %>% summarize_all(mean)

w1_fert_avg$num_hh_fert <- (fert_s11d_named %>% tally())$n
w1_fert_avg
```

pesticide/herbicide

```{r}
ph_w1 <- read_csv('../lsms_data/nigeria/w1/sect11c_plantingw1.csv')
ph_w1
```



## Wave 2 (2012-2013)

```{r}
fert_w2 <- read_csv('../lsms_data/nigeria/w2/sect11d_plantingw2.csv')
```


```{r}
fert_w2 <- fert_w2 %>% select(zone, state, hhid, rep_fert=s11dq1, type_fert=s11dq15) %>% drop_na(rep_fert)
fert_w2

fert_w2[, 4][fert_w2[, 4] == 2] <- 0
fert_w2[fert_w2$rep_fert==0, 5] <- 0
# if fert used but not specified, then put other (4)
fert_w2[((fert_w2$rep_fert==1) & is.na(fert_w2$type_fert)), 5] <- 4

fert_w2_dummy <- cbind(fert_w2, dummy(fert_w2$type_fert, sep='_'))
```

```{r}
w2_named <- fert_w2_dummy %>% rename(no_fert=fert_w2_0, npk=fert_w2_1, urea=fert_w2_2, composite_manure=fert_w2_3, other=fert_w2_4)

w2_named <- w2_named %>% select(-type_fert) %>% mutate(o_fert = composite_manure, io_fert = as.numeric((npk+urea) > 0)) 

```

```{r}
fert_w2_named <- w2_named %>% select(-no_fert) %>% group_by(zone, state, hhid) %>% summarize_all(indicator) %>% drop_na()

w2_fert_avg <- fert_w2_named %>% select(-hhid) %>% group_by(zone, state) %>% summarize_all(mean)

w2_fert_avg$num_hh_fert <- (fert_w2_named %>% tally())$n
w2_fert_avg
```


## Wave 3 (2015-2016)

```{r}
fert_11d_w3 <- read_csv('../lsms_data/nigeria/w3/secta11d_harvestw3.csv')
```

```{r}
fert_w3 <- fert_11d_w3 %>% select(zone, state, hhid, rep_fert=s11dq1, type_fert=s11dq15) %>% drop_na(rep_fert)
fert_w3[fert_w3$state==33, ] # 100% usage

fert_w3[, 4][fert_w3[, 4] == 2] <- 0
fert_w3[fert_w3$rep_fert==0, 5] <- 0
# if fert used but not specified, then put other (4)
fert_w3[((fert_w3$rep_fert==1) & is.na(fert_w3$type_fert)), 5] <- 4

fert_w3_dummy <- cbind(fert_w3, dummy(fert_w3$type_fert, sep='_'))

```

```{r}
w3_named <- fert_w3_dummy %>% rename(no_fert=fert_w3_0, npk=fert_w3_1, urea=fert_w3_2, composite_manure=fert_w3_3, other=fert_w3_4)

w3_named <- w3_named %>% select(-type_fert) %>% mutate(o_fert = composite_manure, io_fert = as.numeric((npk+urea) > 0)) 

```

```{r}
fert_w3_named <- w3_named %>% select(-no_fert) %>% group_by(zone, state, hhid) %>% summarize_all(indicator) %>% drop_na()

w3_fert_avg <- fert_w3_named %>% select(-hhid) %>% group_by(zone, state) %>% summarize_all(mean)

w3_fert_avg$num_hh_fert <- (fert_w3_named %>% tally())$n
w3_fert_avg
```


# Pesticide/Herbicide

## Wave 1

```{r}
w1_pest <- read_csv('../lsms_data/nigeria/w1/sect11c_plantingw1.csv')
w1_pest
```

```{r}
w1_pest <- w1_pest %>% select(zone, state, hhid, pest=s11cq1, herb=s11cq10, pest_quant=s11cq2a, pest_unit=s11cq2b)
w1_pest
```

```{r}
w1_pest[, c('pest', 'herb')][w1_pest[, c('pest', 'herb')] == 2] <- 0
w1_pest[!is.na(w1_pest$pest_quant), c('pest_quant')] # possible to get avg quantity used, but would probably convert to kilos first
```
```{r}
w1_pest <- w1_pest %>% group_by(zone, state, hhid) %>% summarize(pest=indicator(pest), herb=indicator(herb)) %>% drop_na(pest, herb)
w1_pest_avg <- w1_pest %>% select(-hhid) %>% group_by(zone, state) %>% summarize_all(mean)
w1_pest_avg$num_hh_phf <- (w1_pest_avg %>% tally())$n
w1_pest_avg
```

## Wave 2 is missing:

sect11c2_plantingw2

## Wave 3

```{r}
w3_pest <- read_csv('../lsms_data/nigeria/w3/secta11c2_harvestw3.csv')
w3_pest
```



```{r}
w3_pest <- w3_pest %>% select(zone, state, hhid, pest=s11c2q1, herb=s11c2q10)

w3_pest[, c('pest', 'herb')][w3_pest[, c('pest', 'herb')] == 2] <- 0

w3_pest <- w3_pest %>% group_by(zone, state, hhid) %>% summarize(pest=indicator(pest), herb=indicator(herb)) %>% drop_na(pest, herb)

w3_pest_avg <- w3_pest %>% select(-hhid) %>% group_by(zone, state) %>% summarize_all(mean)
w3_pest_avg$num_hh_phf <- (w3_pest_avg %>% tally())$n
w3_pest_avg
```



# Combining
```{r}
w1_final <- w1_fert_avg %>% inner_join(w1_pest_avg)
w3_final <- w3_fert_avg %>% inner_join(w3_pest_avg)
```

```{r}
w1_nigeria <- data.frame(country=rep('nigeria', nrow(w1_final)), start_yr = 2010, end_yr = 2011, w1_final)
w3_nigeria <- data.frame(country=rep('nigeria', nrow(w3_final)), start_yr = 2015, end_yr = 2016, w3_final)
```

```{r}
nigeria_final <- rbind(w1_nigeria, w3_nigeria) %>% 
nigeria_final
```


```{r, eval=FALSE}
a <- read_dta('../lsms_data/nigeria/dta/sect11d_plantingw1.dta')
write_csv(a, '../lsms_data/nigeria/sect11d_plantingw1.csv')

a <- read_dta('../lsms_data/nigeria/dta/sect11d_plantingw2.dta')
write_csv(a, '../lsms_data/nigeria/sect11d_plantingw2.csv')

a <- read_dta('../lsms_data/nigeria/dta/sect11c_plantingw1.dta')
write_csv(a, '../lsms_data/nigeria/sect11c_plantingw1.csv')

a <- read_dta('../lsms_data/nigeria/dta/sect11c1_plantingw2.dta')
write_csv(a, '../lsms_data/nigeria/sect11c1_plantingw2.csv')
```

